import type { StyleSpecification } from "maplibre-gl";
import light from "./decycles-light.json";
import dark from "./decycles-dark.json";

/**
 * Basemap styles for the creator map (MapLibre vector styles).
 *
 * Tiles, fonts and sprites come from OpenFreeMap (https://openfreemap.org):
 * free, no API key, no usage limits, OpenStreetMap data. We previously used
 * CARTO raster tiles, which started requiring an API key and served an
 * "API KEY REQUIRED" watermark instead of the map.
 *
 * The two JSON files are generated by `npm run build:map-styles`
 * (scripts/build-map-styles.cjs) from OpenFreeMap's "positron" and "dark"
 * styles — open-source ports of the CARTO Positron / Dark Matter designs we
 * had before — with our palette on top so the map keeps its look. Customise
 * the map by editing the palettes in that script and re-running it.
 *
 * To self-host later (e.g. Protomaps .pmtiles), only the `sources` in the
 * JSON files need to change.
 */
export const MAP_STYLE_LIGHT = light as unknown as StyleSpecification;
export const MAP_STYLE_DARK = dark as unknown as StyleSpecification;
